### ISSUE TITLE
Can you update for WoW Classic Season of mastery version 1.4.3? Would be awesome, thanks a lot! 

### ISSUE THREAD

**Issue by maximus210793** [HizurosWoWAddOns/BestSellButton#1]
Can you update for WoW Classic Season of mastery version 1.4.3? 
Addon is doing nothing ingame when I click on it.
Would be awesome, thanks a lot!

**Comment by hizuro** [comment]
The latest version (2.2.0-release) is updated for 9.2.5(retail), 2.5.4(TBC) and 1.14.3(classic).
